"""Initial schema

Revision ID: 674260af7933
Revises:
Create Date: 2026-06-06 12:53:39.830057

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "674260af7933"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
