"""add reasons to scanhistory

Revision ID: 478d0bf72381
Revises: 674260af7933
Create Date: 2026-06-07 12:37:23.950212

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "478d0bf72381"
down_revision: Union[str, Sequence[str], None] = "674260af7933"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scanhistory", sa.Column("reasons", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scanhistory", "reasons")
    # ### end Alembic commands ###
